docs/example/message/time.vue

docs: update

---

packages/fusion-ui/components/dialog/src/index.less
packages/fusion-ui/components/dialog/src/index.vue
packages/fusion-ui/components/message/src/index.less

style: dailog和message过渡动画

---

.eslintrc
package.json
packages/components/checkbox/src/index.vue
packages/components/index.ts
packages/theme/css/baseline.less
packages/theme/css/colors.less
packages/theme/css/elevation.less
packages/theme/css/motion.less
packages/theme/css/palette.less
packages/theme/css/shape.less
packages/theme/css/state.less
packages/theme/css/theme.dark.less
packages/theme/css/theme.light.less
packages/theme/css/typography.less
packages/theme/index.ts
packages/theme/package.json
packages/theme/src/palette.ts
packages/theme/src/theme.ts
playground/index.html
playground/src/App.vue
playground/src/main.ts
pnpm-lock.yaml

* Add `theme` system according [Material Design](https://m3.material.io/)

feat: add theme system

---

packages/components/ripple/src/ripple.ts
packages/theme/src/state/index.ts
packages/theme/src/themeRelate/index.ts
packages/theme/src/themeRelate/theme.ts
packages/theme/styles/palette.less
pnpm-lock.yaml

- Fixed the issue of lacking color in the theme

fix: lack of color in theme

---

packages/theme/src/themeRelate/index.ts
packages/theme/src/themeRelate/scheme.ts

- Optimized the import of dynamics by using JSS

style: use jss to write dynamic theme

---

desc.d.ts
packages/hooks/use-checkbox/index.ts
packages/hooks/useJSS/index.ts
packages/theme/src/useTheme/index.ts

- Fixed docs build error
This PR is related to #29

fix: docs build error

---

docs/.vitepress/theme/index.ts
packages/components/ripple/src/index.vue
packages/components/ripple/src/ripple.ts
packages/theme/index.ts
packages/theme/src/useTheme/index.ts
packages/theme/src/useTheme/theme.ts
playground/src/App.vue

- Added `createTheme` and `customizeTheme`
- Added `Funtion` type to color prop of `ripple`

refactor: add Function type to color prop of ripple

---

docs/.vitepress/configuration/components.ts
docs/example/breadcrumb/base.vue
docs/example/breadcrumb/description/en-props-item.ts
docs/example/breadcrumb/description/en-props.ts
docs/example/breadcrumb/description/zh-props-item.ts
docs/example/breadcrumb/description/zh-props.ts
docs/langs/en/components/breadcrumb.md
docs/langs/zh/components/breadcrumb.md
package.json
packages/components/breadcrumb-item/index.ts
packages/components/breadcrumb-item/src/breadcrumb-item.ts
packages/components/breadcrumb-item/src/index.vue
packages/components/breadcrumb/index.ts
packages/components/breadcrumb/src/breadcrumb.ts
packages/components/breadcrumb/src/constants.ts
packages/components/breadcrumb/src/index.less
packages/components/breadcrumb/src/index.vue
packages/components/index.ts
playground/src/App.vue
playground/src/RouterHello.vue
playground/src/main.ts
pnpm-lock.yaml

add breadcrumb component and docs

add breadcrumb

---

packages/components/checkbox/src/index.less
packages/components/ripple/src/index.vue

- Fix the CSS issue of `Ripple` and `Checkbox`

fix: ripple & checkbox hover effect

---

docs/example/checkbox/basic.vue
docs/example/checkbox/color.vue
docs/example/checkbox/icon.vue
docs/example/checkbox/multiple.vue
docs/langs/en/components/checkbox.md
packages/components/checkbox/src/checkbox.ts
packages/components/checkbox/src/index.vue
playground/src/App.vue

- Fixed the binding issue of `Checkbox`
- New feature: use with array
- Updated docs

docs: update checkbox (add 'use with array')

---

docs/example/checkbox/basic.vue
docs/example/checkbox/color.vue
docs/example/checkbox/multiple.vue
docs/langs/en/components/checkbox.md

- Add description for `Checkbox` doc

docs: add description for checkbox

---

packages/components/icon/src/index.vue
packages/components/ripple/src/ripple.ts
packages/theme/src/elevation/elevation.ts
packages/theme/src/elevation/index.ts
packages/theme/src/state/index.ts
packages/theme/src/state/state.ts
packages/theme/src/use-color/index.ts
packages/theme/src/use-theme/index.ts
packages/theme/src/use-theme/theme.ts
packages/theme/styles/elevation.less

- Parse `elevation` to the theme object

feat: add elevations to theme object

---

docs/example/checkbox/color.vue
docs/example/checkbox/label-placement.vue
docs/example/checkbox/label.vue
docs/langs/en/components/checkbox.md
packages/components/checkbox/index.ts
packages/components/form-label/index.ts
packages/components/form-label/src/form-label.ts
packages/components/form-label/src/index.less
packages/components/form-label/src/index.vue
packages/components/index.ts
packages/components/typography/index.ts
packages/components/typography/src/index.vue
packages/components/typography/src/typography.ts
playground/src/App.vue
playground/src/main.ts

- Create new components `FormLabel` and `Typography`
- Update `Checkbox` doc

feat: add new component: FormLabel and Typography

---

docs/example/checkbox/label-placement.vue
docs/example/checkbox/label.vue

- Fix the issue of cannot display `Checkbox`

fix: cannot display checkbox

---

docs/example/checkbox/multiple.vue
docs/langs/en/components/checkbox.md

docs: update Checkbox doc

---

docs/example/button/color.vue
packages/components/checkbox/src/checkbox.ts

- Fixed the issue of checkbox icon

fix: checkbox icon

---

docs/example/button/basic.vue
docs/example/button/filled.vue
docs/example/button/icon.vue
docs/example/button/no-elevation.vue
docs/example/button/outlined.vue
docs/example/button/text.vue
docs/example/checkbox/icon.vue
packages/components/button/__test__/button.spec.ts
packages/components/button/index.ts
packages/components/button/src/button.ts
packages/components/button/src/index.less
packages/components/button/src/index.vue
packages/components/checkbox/src/index.vue
playground/src/App.vue

- Adjusted the slot in `Button` and `Checkbox`
- Added test for `Button`

test: add test cases for button

---

docs/.vitepress/theme/style/var.css

style: fix header style

---

.eslintrc
.prettierrc
packages/components/button-group/__test__/button-group.spec.ts
packages/components/button-group/index.ts
packages/components/button-group/src/button-group.ts
packages/components/button-group/src/index.less
packages/components/button-group/src/index.vue
packages/components/button/src/index.less
packages/components/checkbox/src/index.less
packages/components/icon-button/src/index.less
packages/components/icon-button/src/index.vue
packages/components/index.ts
packages/hooks/index.ts
packages/hooks/use-button/index.ts
playground/src/App.vue
playground/src/main.ts

- Add new component `ButtonGroup`

feat: add button group

---

docs/.vitepress/configuration/components.ts
docs/example/button-group/basic.vue
docs/example/button-group/orientation.vue
docs/example/button-group/size-color.vue
docs/example/button-group/variant.vue
docs/langs/en/components/button-group.md
docs/langs/zh/components/button-group.md
packages/components/button-group/index.ts
packages/components/button-group/src/index.less
playground/src/App.vue
playground/src/style.css

docs: button group

---

docs/.vitepress/theme/index.ts

- Fixed the injection error: `Cannot find 'ThemeContext'`

fix: injection error

---

docs/example/avatar/icon.vue
docs/example/button/icon.vue
docs/example/checkbox/icon.vue
docs/example/icon-button/basic.vue
docs/example/icon-button/color.vue
docs/example/icon-button/size.vue
docs/package.json
pnpm-lock.yaml

- Fixed build error with `fusion-ui-iconify@1.0.44`

fix: build errors

---

docs/.vitepress/configuration/components.ts
docs/.vitepress/theme/index.ts
docs/example/badge/custom.vue
docs/example/icon/basic.vue
docs/example/icon/color.vue
docs/example/icon/description/en-icon-props.ts
docs/example/icon/description/en-svgicon-props.ts
docs/example/icon/description/zh-icon-props.ts
docs/example/icon/description/zh-svgicon-props.ts
docs/example/icon/size.vue
docs/example/icon/svgicon.vue
docs/example/text-field/icon-flexiable.vue
docs/langs/en/components/icon.md
docs/langs/zh/components/icon.md
packages/components/badge/src/badge.ts
packages/components/badge/src/index.vue
packages/components/checkbox/src/index.vue
packages/components/radio/src/index.vue
packages/components/svg-icon/src/index.tsx
packages/components/svg-icon/src/svg-icon.ts
packages/components/text-field/src/index.jss.ts
packages/components/text-field/src/index.vue
packages/theme/src/core/create-theme.ts
playground/src/App.vue
playground/src/components/TextField.vue

- Fix multiple bugs caused by refactoring, for more information, see commits.
- Updated docs for `Icon`

fix & docs: fixed multiple bugs caused by refactoring and updated docs

---

packages/components/alert/index.ts
packages/components/alert/src/alert.ts
packages/components/button-base/src/button-base.ts
packages/components/icon-button/src/icon-button.ts
packages/components/input-base/src/input-base.ts
packages/components/link/src/link.ts
packages/components/svg-icon/src/svg-icon.ts
packages/components/switch/src/switch.ts
packages/components/typography/src/typography.ts
playground/src/components/Alert.vue

fix: cs property

---

playground/src/App.vue

- Updated the usage of message

fix: update the usage of message

---

docs/.vitepress/configuration/components.ts
docs/example/list/highlight.vue

docs: fix known issues

---

packages/components/breadcrumb/src/index.tsx
packages/components/link/src/index.less

- Fixed the bug that clicking the expand (when set the `max`) button will lose some slots

fix: the slots render issue of breadcrumb

---

docs/.vitepress/plugins/code/utils.ts
docs/example/avatar/basic.vue
docs/example/divider/basic.vue
docs/example/divider/full-width.vue
docs/example/divider/inset.vue
docs/example/divider/list.vue
docs/example/divider/orientation.vue
docs/example/divider/text.vue
docs/langs/en/components/divider.md
docs/langs/zh/components/divider.md
packages/components/divider/src/divider.ts
packages/components/divider/src/index.less
packages/components/divider/src/index.tsx
packages/components/list/src/index.tsx
pnpm-lock.yaml

- Updated the doc for `Divider`
- Formatted the preview code

docs: divier

---

.gitignore
interface-ui/package.json

fix: the build error online

---

package.json
pnpm-lock.yaml
scripts/generate.js
scripts/templates/index.ts
scripts/templates/src/__component__.ts
scripts/templates/src/index.jss.ts
scripts/templates/src/index.vue

- Added script and command to generate the template for new components

feat: add script to generate the template for new components

---

tsconfig.json

fix: build error

---

docs/langs/zh/components/button-group.md

fix: dead link in doc

---

docs/.vitepress/config.ts

- Update Algolia configuration

docs: update algolia

---

.github/workflows/deploy.yml

chore: configure pnpm version
